{
    'name': 'Middle East Human Resource Leaves Management',
    'category': 'Human Resources',
    'version': '1.0',
    'sequence': 20,
    'description': """
    """,
    'author': 'ahcec',
    'website': 'http://www.ahcec.com',
    'images': [],
    'depends': [
        'hr_attendance', 'ahcec_hr', 'ahcec_hr_contract', 'hr_payroll', 'hr', 'ahcec_hr_contract_amendment'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/resource_calender_data.xml',
        'data/hr_holiday_status_data.xml',
        'data/hr_payroll_data.xml',
        'data/hr_holidays_data.xml',
        'data/hr_holidays_accrual.xml',
        'views/hr_view.xml',
        'views/hr_public_holidays_view.xml',
        'views/hr_holidays_view.xml',
        'wizard/mass_approve.xml',
        'wizard/leaves_adjust_view.xml',
        # 'wizard/leaves_allocation_view.xml',
        'views/hr_payroll_view.xml',
        # 'views/leave_details.xml',
        'menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
